version: "3"
services:
  web:
    image: quote-service
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 0.75G
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - webnet
networks:
  webnet:
