spring:
  application:
    name: quote-service-docker
    
---    
server:
  port: 8080

---
# HTTP encoding
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
        
---
# INTERNATIONALIZATION (MessageSourceAutoConfiguration)
spring:
  messages:
    basename: messages
    cache-seconds: -1
    encoding: UTF-8
    
---
endpoints:
  health:
    enabled: true
    sensitive: false
  metrics:
    enabled: true
    sensitive: false
  info:
    enabled: true
    sensitive: false
    

